# #####################################################################
# Automatically generated by qmake (2.01a) Mon Apr 13 22:35:17 2009
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += . \
    qtc-gdbmacros
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp \
    mainwindow.cpp \
    qtc-gdbmacros/gdbmacros.cpp
